name: Metrics
on:
  # Schedule updates every day
  schedule: [{cron: "0 0 * * *"}]
  # Allows to run workflow manually
  workflow_dispatch:
  # Run on push to main/master
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: EngDawood
          template: terminal
          base: ""
          config_timezone: Asia/Riyadh
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
